AllCops:
  NewCops: enable
  Exclude:
    - db/**/*
    - bin/**/*
    - config/**/*
    - test/**/*

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Enabled: false